#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://localhost:8761/eureka/
#server:
#  port: 8768   # 8-0
#spring:
#  application:
#    name: fungo-game-config
#  rabbitmq:
#    host: 47.104.87.10
#    port: 5672
#    username: admin
#    password: admin
#  cloud:
#    bus:
#      refresh:
#        enabled: true
#      env:
#        enabled:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/JerryZDL/spring-cloud-config/
#          search-paths:  system
#          username: JerryZDL
#          password: 1993212zdl
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    base-url: http://47.104.87.10:9411/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#        ## 暴露刷新节点 2.x版本需要手动开启
management:
  security:
    enabled: false